[package]
name = "tun2tor"
version = "0.1.0"
authors = ["Conrad Kramer <conrad@kramerapps.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.1.*"
mio = "0.4.*"
byteorder = "0.3.*"

[dependencies.socks]
path = "socks"
